on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: build and push docker image.
    steps:
      - name: debug directory
        run: ls
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hndoss/thanos_snap
          tags: latest